load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "thread_pool",
    srcs = glob(["*.cc", "*.cc"]),
    hdrs = glob(["*.hpp", "*.hpp"]),
    deps = [

    ],
    visibility = [],
)